package POJOS;
// Generated 6 Oct, 2018 4:38:21 PM by Hibernate Tools 3.6.0



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int employeeId;
     private Address address;
     private String firstName;
     private String lastName;

    public Employee() {
    }

	
    public Employee(int employeeId) {
        this.employeeId = employeeId;
    }
    public Employee(int employeeId, Address address, String firstName, String lastName) {
       this.employeeId = employeeId;
       this.address = address;
       this.firstName = firstName;
       this.lastName = lastName;
    }
   
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }




}


